2021-01-22 14:19:30|   0.0|  0.0|INFORM|FME 2020.1.3.0 (20201001 - Build 20632 - WIN64)
2021-01-22 14:19:30|   0.0|  0.0|INFORM|FME_HOME is 'C:\Program Files\FME\'
2021-01-22 14:19:30|   0.0|  0.0|INFORM|FME Database Edition (node locked-crc)
2021-01-22 14:19:30|   0.0|  0.0|INFORM|Serial Number: 0
2021-01-22 14:19:30|   0.0|  0.0|INFORM|Temporary License: 16 days left.
2021-01-22 14:19:30|   0.0|  0.0|INFORM|Machine host name is: DESKTOP-ORJMQCL
2021-01-22 14:19:30|   0.0|  0.0|INFORM|START - ProcessID: 24244, peak process memory usage: 37268 kB, current process memory usage: 37156 kB
2021-01-22 14:19:30|   0.0|  0.0|INFORM|FME Configuration: Command line arguments are `C:\Program Files\FME\fme.exe' `C:/Users/Demo/CesiumCityGMLExp/FME\wb-xlate-1611317967445_15576' `LOG_STANDARDOUT' `YES' `LogCountServerName' `{0fccb829-c9c5-4da6-aa32-cd9659d749d3}' `LOG_TIMINGS' `Yes'
2021-01-22 14:19:30|   0.0|  0.0|INFORM|FME Configuration: Connection Storage: 'C:\Users\Demo\AppData\Roaming\Safe Software\FME\'
2021-01-22 14:19:31|   0.6|  0.6|INFORM|Shared folders for formats are : C:\Program Files\FME\datasources;C:\Users\Demo\Documents\FME\Formats
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Shared folders for transformers are : C:\Users\Demo\AppData\Roaming\Safe Software\FME\Packages\20632-win64\transformers;C:\Program Files\FME\transformers;C:\Users\Demo\AppData\Roaming\Safe Software\FME\FME Store\Transformers
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Shared folders for coordinate systems are : C:\Users\Demo\Documents\FME\CoordinateSystems
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Shared folders for coordinate system exceptions are : C:\Users\Demo\Documents\FME\CoordinateSystemExceptions
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Shared folders for coordinate system grid overrides are : C:\Users\Demo\Documents\FME\CoordinateSystemGridOverrides
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Shared folders for CS-MAP transformation exceptions are : C:\Users\Demo\Documents\FME\CsmapTransformationExceptions
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Shared folders for transformer categories are : C:\Users\Demo\Documents\FME\TransformerCategories
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Reader Keyword is `MULTI_READER'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Writer Keyword is `NULL_DEST'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Writer Group Definition Keyword is `NULL_DEST_DEF'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Reader type is `MULTI_READER'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Writer type is `NULL'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: No destination coordinate system set
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Current working folder is `C:\Users\Demo\CesiumCityGMLExp\FME'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Temporary folder is `C:\Users\Demo\AppData\Local\Temp\wbrun_1610628268392_15576\fmetmp_1611317969479_15576', set from environment variable `FME_TEMP'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: FME_HOME is `C:\Program Files\FME\'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: FME_BASE is 'no'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: FME_MF_DIR is 'C:\Users\Demo\CesiumCityGMLExp\FME/'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: FME_MF_NAME is 'kafkatest.fmw'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: FME_PRODUCT_NAME is 'FME(R) 2020.1.3.0'
2021-01-22 14:19:31|   0.6|  0.0|INFORM|System Status: 42.15 GB of disk space available in the FME temporary folder (C:\Users\Demo\AppData\Local\Temp\wbrun_1610628268392_15576\fmetmp_1611317969479_15576)
2021-01-22 14:19:31|   0.6|  0.0|INFORM|System Status: 15.96 GB of physical memory available
2021-01-22 14:19:31|   0.6|  0.0|INFORM|System Status: 31.96 GB of virtual memory available
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Operating System: Microsoft Windows 10 64-bit  (Build 19041)
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Platform: WIN64
2021-01-22 14:19:31|   0.6|  0.0|INFORM|Locale: en_FI
2021-01-22 14:19:31|   0.6|  0.0|INFORM|System Encoding: windows-1252
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Start freeing memory when the process exceeds 47.87 GB
2021-01-22 14:19:31|   0.6|  0.0|INFORM|FME Configuration: Stop freeing memory when the process is below 35.90 GB
2021-01-22 14:19:32|   0.6|  0.0|INFORM|Creating writer for format: NULL (Nothing)
2021-01-22 14:19:32|   0.6|  0.0|INFORM|Trying to find a DYNAMIC plugin for writer named `NULL'
2021-01-22 14:19:32|   0.6|  0.0|INFORM|Loaded module 'NULL' from file 'C:\Program Files\FME\plugins/NULL.dll'
2021-01-22 14:19:32|   0.6|  0.0|INFORM|FME API version of module 'NULL' matches current internal version (3.8 20200115)
2021-01-22 14:19:32|   0.6|  0.0|INFORM|Creating reader for format: 
2021-01-22 14:19:32|   0.6|  0.0|INFORM|MULTI_READER(MULTI_READER): Will fail with first member reader failure
2021-01-22 14:19:32|   0.6|  0.0|INFORM|Using Multi Reader with keyword `MULTI_READER' to read multiple datasets
2021-01-22 14:19:32|   0.6|  0.0|INFORM|FME API version of module 'NULL' matches current internal version (3.8 20200115)
2021-01-22 14:19:32|   0.6|  0.0|INFORM|FME API version of module 'NULL' matches current internal version (3.8 20200115)
2021-01-22 14:19:32|   0.6|  0.0|INFORM|Loaded module 'Geometry_func' from file 'C:\Program Files\FME\plugins/Geometry_func.dll'
2021-01-22 14:19:32|   0.6|  0.0|INFORM|FME API version of module 'Geometry_func' matches current internal version (3.8 20200115)
2021-01-22 14:19:32|   0.6|  0.0|INFORM|Loaded module 'LogCount_func' from file 'C:\Program Files\FME\plugins/LogCount_func.dll'
2021-01-22 14:19:32|   0.6|  0.0|INFORM|FME API version of module 'LogCount_func' matches current internal version (3.8 20200115)
2021-01-22 14:19:32|   0.7|  0.0|INFORM|Loaded module 'PythonFactory' from file 'C:\Program Files\FME\plugins/PythonFactory.dll'
2021-01-22 14:19:32|   0.7|  0.0|INFORM|FME API version of module 'PythonFactory' matches current internal version (3.8 20200115)
2021-01-22 14:19:32|   0.7|  0.0|INFORM|The workspace does not contain user Python. FME will attempt to use a Python 3.7+ interpreter
2021-01-22 14:19:32|   0.7|  0.0|INFORM|Using Python interpreter from `C:\Program Files\FME\fmepython37\python37.dll' with PYTHONHOME `C:\Program Files\FME\fmepython37'
2021-01-22 14:19:32|   0.7|  0.0|INFORM|Python version 3.7 loaded successfully
2021-01-22 14:19:32|   0.7|  0.1|INFORM|Emptying factory pipeline
2021-01-22 14:19:32|   0.7|  0.0|STATS |Storing feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_defaultPointMetadata -1 2 fo 0 CREATED  0  3452bb17bc34b3496fbb967754bec69a4ea330db.ffsupdating'
2021-01-22 14:19:32|   0.8|  0.0|STATS |Storing feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 1 INITIATOR  0  39070cedb32d7b8651b286264c361491a3b86b44.ffsupdating'
2021-01-22 14:19:34|   2.0|  1.2|INFORM|KafkaConnector: The connector is being assigned...
2021-01-22 14:19:34|   2.0|  0.0|INFORM|KafkaConnector: Receiving batch of 10 message(s)...
2021-01-22 14:19:35|   2.0|  0.1|WARN  |KafkaConnector: An error was encountered: '_SSL: ssl://kafka-28a49ead-fvh-331-datatrials.aivencloud.com:12125/bootstrap: SSL handshake failed: .\ssl\s3_clnt.c:1269: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 98ms in state CONNECT)'. Please check host names and ports, security settings, and credentials
2021-01-22 14:19:35|   2.0|  0.0|WARN  |KafkaConnector: An error was encountered: '_ALL_BROKERS_DOWN: 1/1 brokers are down'. Please check host names and ports, security settings, and credentials
2021-01-22 14:19:36|   2.1|  0.0|WARN  |KafkaConnector: An error was encountered: '_SSL: ssl://kafka-28a49ead-fvh-331-datatrials.aivencloud.com:12125/bootstrap: SSL handshake failed: .\ssl\s3_clnt.c:1269: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 69ms in state CONNECT)'. Please check host names and ports, security settings, and credentials
2021-01-22 14:19:37|   2.1|  0.0|WARN  |KafkaConnector: An error was encountered: '_SSL: ssl://kafka-28a49ead-fvh-331-datatrials.aivencloud.com:12125/bootstrap: SSL handshake failed: .\ssl\s3_clnt.c:1269: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 53ms in state CONNECT)'. Please check host names and ports, security settings, and credentials
2021-01-22 14:19:38|   2.1|  0.0|WARN  |KafkaConnector: An error was encountered: '_SSL: ssl://kafka-28a49ead-fvh-331-datatrials.aivencloud.com:12125/bootstrap: SSL handshake failed: .\ssl\s3_clnt.c:1269: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 56ms in state CONNECT)'. Please check host names and ports, security settings, and credentials
2021-01-22 14:19:39|   2.1|  0.0|WARN  |KafkaConnector: An error was encountered: '_SSL: ssl://kafka-28a49ead-fvh-331-datatrials.aivencloud.com:12125/bootstrap: SSL handshake failed: .\ssl\s3_clnt.c:1269: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 49ms in state CONNECT)'. Please check host names and ports, security settings, and credentials
2021-01-22 14:19:41|   2.2|  0.0|WARN  |KafkaConnector: An error was encountered: '_SSL: ssl://kafka-28a49ead-fvh-331-datatrials.aivencloud.com:12125/bootstrap: SSL handshake failed: .\ssl\s3_clnt.c:1269: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:  (after 51ms in state CONNECT)'. Please check host names and ports, security settings, and credentials
2021-01-22 15:29:04|   0.0|  0.0|INFORM|FME 2020.1.3.0 (20201001 - Build 20632 - WIN64)
2021-01-22 15:29:04|   0.0|  0.0|INFORM|FME_HOME is 'C:\Program Files\FME\'
2021-01-22 15:29:04|   0.0|  0.0|INFORM|FME Database Edition (node locked-crc)
2021-01-22 15:29:04|   0.0|  0.0|INFORM|Serial Number: 0
2021-01-22 15:29:04|   0.0|  0.0|INFORM|Temporary License: 16 days left.
2021-01-22 15:29:04|   0.0|  0.0|INFORM|Machine host name is: DESKTOP-ORJMQCL
2021-01-22 15:29:04|   0.0|  0.0|INFORM|START - ProcessID: 19580, peak process memory usage: 37292 kB, current process memory usage: 37180 kB
2021-01-22 15:29:04|   0.0|  0.0|INFORM|FME Configuration: Command line arguments are `C:\Program Files\FME\fme.exe' `C:/Users/Demo/CesiumCityGMLExp/FME\wb-xlate-1611322142696_15576' `LOG_STANDARDOUT' `YES' `LogCountServerName' `{4e4eca52-7100-46c5-96d0-ef024f46572c}' `LOG_TIMINGS' `Yes'
2021-01-22 15:29:04|   0.0|  0.0|INFORM|FME Configuration: Connection Storage: 'C:\Users\Demo\AppData\Roaming\Safe Software\FME\'
2021-01-22 15:29:05|   0.5|  0.5|INFORM|Shared folders for formats are : C:\Program Files\FME\datasources;C:\Users\Demo\Documents\FME\Formats
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Shared folders for transformers are : C:\Users\Demo\AppData\Roaming\Safe Software\FME\Packages\20632-win64\transformers;C:\Program Files\FME\transformers;C:\Users\Demo\AppData\Roaming\Safe Software\FME\FME Store\Transformers
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Shared folders for coordinate systems are : C:\Users\Demo\Documents\FME\CoordinateSystems
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Shared folders for coordinate system exceptions are : C:\Users\Demo\Documents\FME\CoordinateSystemExceptions
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Shared folders for coordinate system grid overrides are : C:\Users\Demo\Documents\FME\CoordinateSystemGridOverrides
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Shared folders for CS-MAP transformation exceptions are : C:\Users\Demo\Documents\FME\CsmapTransformationExceptions
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Shared folders for transformer categories are : C:\Users\Demo\Documents\FME\TransformerCategories
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Reader Keyword is `MULTI_READER'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Writer Keyword is `NULL_DEST'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Writer Group Definition Keyword is `NULL_DEST_DEF'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Reader type is `MULTI_READER'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Writer type is `NULL'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: No destination coordinate system set
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Current working folder is `C:\Users\Demo\CesiumCityGMLExp\FME'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Temporary folder is `C:\Users\Demo\AppData\Local\Temp\wbrun_1610628268392_15576\fmetmp_1611322144146_15576', set from environment variable `FME_TEMP'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: FME_HOME is `C:\Program Files\FME\'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: FME_BASE is 'no'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: FME_MF_DIR is 'C:\Users\Demo\CesiumCityGMLExp\FME/'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: FME_MF_NAME is 'kafkatest.fmw'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: FME_PRODUCT_NAME is 'FME(R) 2020.1.3.0'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|System Status: 42.15 GB of disk space available in the FME temporary folder (C:\Users\Demo\AppData\Local\Temp\wbrun_1610628268392_15576\fmetmp_1611322144146_15576)
2021-01-22 15:29:05|   0.5|  0.0|INFORM|System Status: 15.96 GB of physical memory available
2021-01-22 15:29:05|   0.5|  0.0|INFORM|System Status: 31.96 GB of virtual memory available
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Operating System: Microsoft Windows 10 64-bit  (Build 19041)
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Platform: WIN64
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Locale: en_FI
2021-01-22 15:29:05|   0.5|  0.0|INFORM|System Encoding: windows-1252
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Start freeing memory when the process exceeds 47.87 GB
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME Configuration: Stop freeing memory when the process is below 35.90 GB
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Creating writer for format: NULL (Nothing)
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Trying to find a DYNAMIC plugin for writer named `NULL'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Loaded module 'NULL' from file 'C:\Program Files\FME\plugins/NULL.dll'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME API version of module 'NULL' matches current internal version (3.8 20200115)
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Creating reader for format: 
2021-01-22 15:29:05|   0.5|  0.0|INFORM|MULTI_READER(MULTI_READER): Will fail with first member reader failure
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Using Multi Reader with keyword `MULTI_READER' to read multiple datasets
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME API version of module 'NULL' matches current internal version (3.8 20200115)
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME API version of module 'NULL' matches current internal version (3.8 20200115)
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Loaded module 'Geometry_func' from file 'C:\Program Files\FME\plugins/Geometry_func.dll'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME API version of module 'Geometry_func' matches current internal version (3.8 20200115)
2021-01-22 15:29:05|   0.5|  0.0|INFORM|Loaded module 'LogCount_func' from file 'C:\Program Files\FME\plugins/LogCount_func.dll'
2021-01-22 15:29:05|   0.5|  0.0|INFORM|FME API version of module 'LogCount_func' matches current internal version (3.8 20200115)
2021-01-22 15:29:05|   0.6|  0.0|INFORM|Loaded module 'PythonFactory' from file 'C:\Program Files\FME\plugins/PythonFactory.dll'
2021-01-22 15:29:05|   0.6|  0.0|INFORM|FME API version of module 'PythonFactory' matches current internal version (3.8 20200115)
2021-01-22 15:29:05|   0.6|  0.0|INFORM|The workspace does not contain user Python. FME will attempt to use a Python 3.7+ interpreter
2021-01-22 15:29:05|   0.6|  0.0|INFORM|Using Python interpreter from `C:\Program Files\FME\fmepython37\python37.dll' with PYTHONHOME `C:\Program Files\FME\fmepython37'
2021-01-22 15:29:05|   0.6|  0.0|INFORM|Python version 3.7 loaded successfully
2021-01-22 15:29:05|   0.6|  0.1|INFORM|Emptying factory pipeline
2021-01-22 15:29:05|   0.6|  0.0|STATS |Storing feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_defaultPointMetadata -1 2 fo 0 CREATED  0  3452bb17bc34b3496fbb967754bec69a4ea330db.ffsupdating'
2021-01-22 15:29:05|   0.7|  0.0|STATS |Storing feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 1 INITIATOR  0  c7cd219b7d2a1463b86712c747d7f376b313c302.ffsupdating'
2021-01-22 15:29:06|   1.8|  1.2|STATS |Storing feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 2 _lt_REJECTED_gt_  0  36855a7e41735157f67a536507738151c57ca0ed.ffsupdating'
2021-01-22 15:29:06|   1.8|  0.0|FATAL |The below feature caused the translation to be terminated
2021-01-22 15:29:06|   1.8|  0.0|STATS |Storing feature(s) to FME feature store file `C:\Users\Demo\CesiumCityGMLExp\FME\kafkatest_log.ffs'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Feature Type: `FEATURE_TYPE'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Attribute(32 bit unsigned integer): `Kafka' has value `0'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Attribute(string)                 : `fme_feature_type' has value `defaultPointMetadata'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Attribute(string)                 : `fme_geometry' has value `fme_undefined'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Attribute(encoded: UTF-8)         : `fme_rejection_code' has value `ERROR_DURING_PROCESSING'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Attribute(encoded: UTF-8)         : `fme_rejection_message' has value `An error was encountered while attempting to create the Consumer client: 'Failed to create consumer: ssl.ca.location failed: .\crypto\x509\by_file.c:254: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib: '. Please check host names and ports, security settings, and credentials'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Attribute(string)                 : `fme_type' has value `fme_no_geom'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Coordinate System: `'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Geometry Type: IFMENull
2021-01-22 15:29:06|   1.8|  0.0|INFORM|===========================================================================
2021-01-22 15:29:06|   1.8|  0.0|ERROR |KafkaConnector_<Rejected> (TeeFactory): KafkaConnector_<Rejected>: Termination Message: 'KafkaConnector output a <Rejected> feature.  To continue translation when features are rejected, change 'Workspace Parameters' > Translation > 'Rejected Feature Handling' to 'Continue Translation''
2021-01-22 15:29:06|   1.8|  0.0|ERROR |KafkaConnector_<Rejected>: Termination Message: 'KafkaConnector output a <Rejected> feature.  To continue translation when features are rejected, change 'Workspace Parameters' > Translation > 'Rejected Feature Handling' to 'Continue Translation''
2021-01-22 15:29:06|   1.8|  0.0|WARN  |
2021-01-22 15:29:06|   1.8|  0.0|ERROR |Error encountered while calling method `input'
2021-01-22 15:29:06|   1.8|  0.0|FATAL |f_7 (PythonFactory): PythonFactory failed to process feature
2021-01-22 15:29:06|   1.8|  0.0|ERROR |f_7 (PythonFactory): A fatal error has occurred. Check the logfile above for details
2021-01-22 15:29:06|   1.8|  0.0|STATS |Stored 1 feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 1 INITIATOR  0  c7cd219b7d2a1463b86712c747d7f376b313c302.ffsupdating'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Saving spatial index into file 'C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 1 INITIATOR  0  c7cd219b7d2a1463b86712c747d7f376b313c302.fsi'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Finished saving spatial index into file 'C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 1 INITIATOR  0  c7cd219b7d2a1463b86712c747d7f376b313c302.fsi'
2021-01-22 15:29:06|   1.8|  0.0|STATS |Stored 1 feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_defaultPointMetadata -1 2 fo 0 CREATED  0  3452bb17bc34b3496fbb967754bec69a4ea330db.ffsupdating'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Saving spatial index into file 'C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_defaultPointMetadata -1 2 fo 0 CREATED  0  3452bb17bc34b3496fbb967754bec69a4ea330db.fsi'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Finished saving spatial index into file 'C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_defaultPointMetadata -1 2 fo 0 CREATED  0  3452bb17bc34b3496fbb967754bec69a4ea330db.fsi'
2021-01-22 15:29:06|   1.8|  0.0|STATS |Stored 1 feature(s) to FME feature store file `C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 2 _lt_REJECTED_gt_  0  36855a7e41735157f67a536507738151c57ca0ed.ffsupdating'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Saving spatial index into file 'C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 2 _lt_REJECTED_gt_  0  36855a7e41735157f67a536507738151c57ca0ed.fsi'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Finished saving spatial index into file 'C:\Users\Demo\AppData\Local\Temp\wb-cache--HXVtiO\Main_KafkaConnector -1 3 fo 2 _lt_REJECTED_gt_  0  36855a7e41735157f67a536507738151c57ca0ed.fsi'
2021-01-22 15:29:06|   1.8|  0.0|ERROR |A fatal error has occurred. Check the logfile above for details
2021-01-22 15:29:06|   1.8|  0.0|INFORM|Translation FAILED with 7 error(s) and 1 warning(s) (0 feature(s) output)
2021-01-22 15:29:06|   1.8|  0.0|STATS |Stored 1 feature(s) to FME feature store file `C:\Users\Demo\CesiumCityGMLExp\FME\kafkatest_log.ffs'
2021-01-22 15:29:06|   1.8|  0.0|INFORM|FME Session Duration: 2.0 seconds. (CPU: 0.8s user, 0.6s system)
2021-01-22 15:29:06|   1.8|  0.0|INFORM|END - ProcessID: 19580, peak process memory usage: 69192 kB, current process memory usage: 69156 kB
